### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pcharlesme**
Here are three key changes 
Detailed Participation Guidelines and Community Engagement and Collaboration.

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]
I like it

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
eaaY

**Review by naxoootcnjncgjnnxfhjjv — COMMENTED** [review]
[-](url)

**Review by naxoootcnjncgjnnxfhjjv — COMMENTED** [review]
``

**Review by naxoootcnjncgjnnxfhjjv — COMMENTED** [review]
unu

**Pull request merged**
